### PR TITLE
Had to make these changes to make it work...

### PR DESCRIPTION
**Pull request by Benjamin-FC**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@jennyraj this doesn't sound right... angular2 is already distributed with traceur so no need to add it separately. Also you are suggesting a _very_ old traceur runtime.

Are you sure that you've cleaned up your node_modules folder and did fresh npm install?

**Comment by Benjamin-FC** [comment]
yes, I just installed npm 4.0! Is it the issue?

**Comment by pkozlowski-opensource** [comment]
npm 4.0? I thought that the latest is 3.3.3... It _could_ be an issue since npm 3.x de-dupes deps by default, AFAIK. But still, it wouldn't require explicit dependency on traceur....

**Comment by Benjamin-FC** [comment]
Sorry, I mean NodeJS 4.0

Date: Mon, 14 Sep 2015 11:44:55 -0700

**Comment by Benjamin-FC** [comment]
Seems to be related to NodeJS 4.0, Closing the request

**Pull request closed without merging**
